# Generated by Django 3.1 on 2020-08-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20200818_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='label',
            field=models.CharField(blank=True, choices=[('OUT OF STOK', 'OUT OF STOK'), ('NEW', 'NEW')], max_length=200, null=True),
        ),
    ]
