# Generated by Django 3.1 on 2020-08-18 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20200818_1207'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ImageProduct',
        ),
    ]
